version: '3.3'
services:
  mariadb:
    image: "mariadb:10.1.37"
    container_name: "typeorm-mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

